[tool.poetry]
name = "opendis"
version = "0.1.0"
description = ""
authors = ["Don McGregor <mcgredo@nps.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
